#!/bin/bash

echo "🚀 Yo Store - Render.com Deploy"
echo "==============================="

echo "📋 Next steps for Render.com deployment:"
echo ""
echo "1. 🌐 Go to Render.com:"
echo "   https://render.com"
echo ""
echo "2. 🔐 Sign up/Login with GitHub"
echo ""
echo "3. 📦 Create Web Service:"
echo "   - Click 'New +' → 'Web Service'"
echo "   - Connect GitHub repo: osman-shamshidov/yo_store"
echo ""
echo "4. ⚙️ Configure settings:"
echo "   - Name: yo-store"
echo "   - Environment: Python 3"
echo "   - Build Command: pip install -r requirements.txt"
echo "   - Start Command: python main.py"
echo ""
echo "5. 🔑 Set environment variables:"
echo "   - TELEGRAM_BOT_TOKEN=your_bot_token"
echo "   - SECRET_KEY=your_secret_key"
echo "   - DEBUG=False"
echo "   - HOST=0.0.0.0"
echo "   - PORT=\$PORT"
echo ""
echo "6. 🗄️ Create PostgreSQL database:"
echo "   - Click 'New +' → 'PostgreSQL'"
echo "   - Name: yo-store-db"
echo "   - Copy DATABASE_URL to Web Service"
echo ""
echo "7. 📱 Configure Telegram bot with Render URL"
echo ""
echo "📖 Full instructions: RENDER_DEPLOY.md"
echo "🎉 Happy deploying on Render!"
